spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: ${FORWARD_HEADERS_STRATEGY:none}
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}

spotyourslot:
  security:
    allowed-origin: ${ALLOWED_ORIGIN}
